### ISSUE TITLE
Option to exclude particular schema from OpenAPI

### ISSUE THREAD

**Issue by pavelsr** [preaction/Yancy#105]
I want that one schema be editable only from Yancy form.
Is there any out-of-the box way to do that?

Ideally if there was an option, let's call it `x-api-hidden`, that does inverse logic to `x-hidden`:

| Option \ Exclude from | API | Rich form
| ------------- | ------------- | ------------- |
| [x-hidden](https://metacpan.org/pod/distribution/Yancy/lib/Yancy/Help/Config.pod#x-hidden)  | -  | + |
| x-api-hidden | + | - |
| [x-ignore](https://metacpan.org/pod/distribution/Yancy/lib/Yancy/Help/Config.pod#x-hidden)  |  +  | + |

**Comment by preaction** [comment]
Do you mean editable only by `$c->yancy->form->form_for()`, or editable by the Yancy editor application (which uses the API)? `x-ignore` should make it not available to the API, but still available to `$c->yancy->form->form_for()`.
