### ISSUE TITLE
Browser gets no response on get/post_register when not allowed

### ISSUE THREAD

**Issue by uniejo** [preaction/Yancy#108]
My browser seems to reload a number of times, due to no reply (when allow_register is not set)
I suggest adding the following not_found replies:

lib/Yancy/Plugin/Auth/Password.pm VERSION 1.059 :

 sub _get_register {
     my ( $self, $c ) = @_;
     if ( !$self->allow_register ) {
         $c->app->log->error( 'Registration not allowed (set allow_register)' );
+        $c->reply->not_found;
         return;
     }
     return $c->render( 'yancy/auth/password/register',
         plugin => $self,
     );
 }

 sub _post_register {
     my ( $self, $c ) = @_;
     if ( !$self->allow_register ) {
         $c->app->log->error( 'Registration not allowed (set allow_register)' );
+        $c->reply->not_found;
         return;
     }

**Comment by preaction** [comment]
That's a great solution, thanks! I'll get this in right away
