### ISSUE TITLE
Typo in yancy/app.js

### ISSUE THREAD

**Issue by uniejo** [preaction/Yancy#109]
A recent change prevents loading of yancy editor.
It looks like a typo with a 's' too much  ( s/definitions/definition/ ).
After removing the 's', it loads again.

--- a/lib/Mojolicious/Plugin/Yancy/resources/public/yancy/app.js
+++ b/lib/Mojolicious/Plugin/Yancy/resources/public/yancy/app.js
@@ -592,7 +592,7 @@ var app = window.Yancy = new Vue({
 
                 for ( var propKey in definition.properties ) {
                     var prop = definition.properties[ propKey ];
-                    if ( prop[ 'x-html-field' ] && definitions.properties[ prop['x-html-field'] ] ) {
+                    if ( prop[ 'x-html-field' ] && definition.properties[ prop['x-html-field'] ] ) {
                         definition.properties[ prop['x-html-field' ] ][ 'x-hidden' ] = true;
                     }
                 }

**Comment by preaction** [comment]
Thanks! Clearly there's no test for that feature (markdown fields in the editor), so I'll have to add one to prevent this from happening again
