### ISSUE TITLE
CORS support for remote API access

### ISSUE THREAD

**Issue by mario-minati** [preaction/Yancy#39]
We need CORS support to handle remote access onto the api routes.
As Yancy makes use of Mojolicious::Plugin::OpenAPI there is some cors support out of the box, if the api controller is extended as described in [Mojolicious::Plugin::OpenAPI::Cors](https://metacpan.org/pod/Mojolicious::Plugin::OpenAPI::Cors). 

Is this something that would be for core Yancy or shall we put that into an custom controller?

**Comment by preaction** [comment]
It absolutely should be in the core Yancy editor. CORS is a real problem and we should be doing everything we can to make this as secure as possible out-of-the-box (it's why Yancy::Controller::Yancy has CORS for non-API requests).

So, this also means there's a way to do CORS for Yancy::Controller::Yancy API requests. That's good to know, thanks!

**Comment by mario-minati** [comment]
There is currently a show stopper upstream in jhthorsen/mojolicious-plugin-openapi#99

**Comment by mario-minati** [comment]
One solution would be to automatically add `OPTIONS` request to every route during Yancy setup and do the CORS stuff in Yancy, but I'd regard that an ugly hack.

**Comment by mario-minati** [comment]
We made some additions for Mojolicious::Plugin::OpenAPI which seem to fix the problem. We posted them for the time being in jhthorsen/mojolicious-plugin-openapi#99.

An other minor fix has been made for Yancy so it could hand the CORS related config to the OpenAPI object during setup:
```
diff --git a/app/lib/Mojolicious/Plugin/Yancy.pm b/app/lib/Mojolicious/Plugin/Yancy.pm
index ac93693..b82886b 100644
--- a/app/lib/Mojolicious/Plugin/Yancy.pm
+++ b/app/lib/Mojolicious/Plugin/Yancy.pm
@@ -498,6 +498,7 @@ sub register {
         route => $route->any( '/api' )->name( 'yancy.api' ),
         spec => $spec,
         default_response_name => '_Error',
+        cors => $config->{cors} || {},
     } );
     $app->helper( 'yancy.openapi' => sub { $openapi } );
```

With the changes in Mojolicious::Plugin::OpenAPI the controller can be easily extend with CORS support, you just invoke the following before validating the request (can be chained):
```
$c->openapi->cors();
```

As the CODE code is transparent for non CORS request it could be inserted into the default api controller.

An extended controller looks like:
```
package Yancy::Controller::Yancy::CorsAPI;
use Mojo::Base 'Yancy::Controller::Yancy::API';

sub list_items {
    my ( $c ) = @_;
    $c->openapi->cors();
    $c->SUPER::list_items || return;
}

sub add_item {
    my ( $c ) = @_;
    $c->openapi->cors();
    $c->SUPER::add_item || return;
}

sub get_item {
    my ( $c ) = @_;
    $c->openapi->cors();
    $c->SUPER::get_item || return;
}

sub set_item {
    my ( $c ) = @_;
    $c->openapi->cors();
    $c->SUPER::set_item || return;
}

sub delete_item {
    my ( $c ) = @_;
    $c->openapi->cors();
    $c->SUPER::delete_item || return;
}

1;
 
```

**Comment by preaction** [comment]
I would be okay with adding `OPTIONS` request handling to all of Yancy's controllers for CORS support regardless of the result of your open thread on the Mojolicious::Plugin::OpenAPI issue tracker: The other controllers (Yancy::Controller::Yancy and subclasses) all provide APIs as well, and would need CORS support for cross-origin requests. I'll open a new ticket for that, though, as that's not related to the current issue (if that support happens first, though, it might make the CORS inside Mojolicious::Plugin::OpenAPI unnecessary for Yancy's uses).

**Comment by preaction** [comment]
The linked ticket (https://github.com/jhthorsen/mojolicious-plugin-openapi/issues/99) is closed, so what's the next steps to add CORS support for Yancy?
