### ISSUE TITLE
OpenAPI securityDefinitions support

### ISSUE THREAD

**Issue by mohawk2** [preaction/Yancy#40]
After discussion on `#yancy`, here are some thoughts. `Mojolicious::Plugin::OpenAPI::Security` has the basics of support for `securityDefinitions` (SD), which `Mojolicious::Plugin::Yancy` could expand on.

# OpenAPI spec -> Yancy

If an OpenAPI spec with SD is provided, this could be enabled by a `Yancy::Plugin::Auth::DispatchSecurity` (only with maybe a better name). Each `Yancy::Plugin::Auth::*` module would register itself with the dispatcher (having been loaded by Yancy as a plugin), which  that would read the SD, and on loading `Mojolicious::Plugin::OpenAPI` would provide the appropriate callback according to the SD.

# Yancy -> OpenAPI spec

Similarly, if there are no SD provided, but a `Yancy::Plugin::Auth::*` is loaded with the right config, it could register itself (by its return values - perhaps plugins should more widely return things that want to be passed to the OpenAPI plugin and/or spec) and end up being added to the spec's SD.

**Comment by preaction** [comment]
One issue that jumps out right away is the need for registration: This requires us to load every auth module before we know if we can properly configure Yancy for the given OpenAPI securityDefinitions.

The central, pluggable auth module for Yancy (the one that dispatches to other auth modules as necessary) is just going to be Yancy::Plugin::Auth.

Do you perhaps have some links to resources about securityDefinitions you could add to this thread while we figure out what we can do?

**Comment by mohawk2** [comment]
This spells it out nicely: https://swagger.io/docs/specification/2-0/authentication/

This is the canonical spec - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md - search for "Security Definitions".

My thought was that you wouldn't need to load every possible auth module, just the specified ones for that Yancy instance's config; so you might have:

```
{
 plugins => [ [ 'Auth::MyFunky' ] ]
}
```

which would on loading register itself with `Yancy::Plugin::Auth`.

**Comment by preaction** [comment]
The OpenAPI code has moved to [Yancy::Plugin::OpenAPI](https://metacpan.org/pod/Yancy::Plugin::OpenAPI), so there's no need to do anything additional here in Yancy.
