### ISSUE TITLE
Standalone mode config file lookup

### ISSUE THREAD

**Issue by pplu** [preaction/Yancy#47]
Hi,

I was trying to use Yancy in standalone mode. My setup creates a cpanfile declaring Yancy and dependencies, carton installed. I was creating the yancy.conf file in the homedir of the project, but it didn't seem to get loaded. A bit of investigating shows that the yancy.conf is looked up in `local/lib/perl5`, which I wasn't expecting.

```
pplu@clamps:~/yancy$ carton exec strace yancy daemon 2>&1 | grep conf
[...]
stat("/home/pplu/yancy/local/lib/perl5/yancy.development.conf", 0x788680) = -1 ENOENT (No such file or directory)
stat("/home/pplu/yancy/local/lib/perl5/yancy.conf", 0x788680) = -1 ENOENT (No such file or directory)
[...]
```

Any ideas on how to fix this?

**Comment by preaction** [comment]
For now, set the `MOJO_HOME` environment variable to the full path to the directory containing the config file, or set the `MOJO_CONFIG` environment variable to the full path to the config file. The `MOJO_HOME` directory is also used to find templates and static files, so I consider that the better solution.

In the long term: This is the wrong default behavior, and I consider it a bug. The default "home" directory of the `yancy` standalone command should be the current working directory unless `MOJO_HOME` is set.
