### ISSUE TITLE
better handling of filters based on column type

### ISSUE THREAD

**Issue by rmallah** [preaction/Yancy#48]
https://github.com/preaction/Yancy/blob/5081d3d6434239043921c6bd6fa40913d9295ded/lib/Yancy/Controller/Yancy/API.pm#L72-L79

Hi , 
The code does only ilike search. we can have equality search for integers.
Shall i submit a pull request here? (ie in github)

regds
mallah.

**Comment by mohawk2** [comment]
This will be fixed and therefore can be closed once #59 is merged.
