### ISSUE TITLE
 Error validating new item in schema "users"

### ISSUE THREAD

**Issue by pavelsr** [preaction/Yancy#79]
When I played with your CMS and [demo project](https://github.com/preaction/Yancy/tree/master/eg/test-app) I got errors when trying to add new user:

```
Error validating new item in schema "users": /plugin: Expected string - got null
```

```
Error validating new item in schema "users":  (/created)
```

How to debug such errors ?

**Comment by preaction** [comment]
What command/steps were you running when you got that error? It looks like you're creating a user but not providing a `plugin` value or a `created` value. The `plugin` needs to be some string (part of supporting multiple authentication methods in Yancy::Plugin::Auth), and the `created` needs to be an ISO8601 datetime (`YYYY-MM-DD HH:MM:SS`, like `2019-01-01 14:45:12`).

**Comment by preaction** [comment]
Closing this issue until further information can be provided
