### ISSUE TITLE
I can write only in English

### ISSUE THREAD

**Issue by dagmatritsa** [preaction/Yancy#82]
How can I write in another languege?
#!/usr/bin/env perl
use utf8;
use Mojolicious::Lite;
binmode(STDOUT, ":utf8");
binmode(STDIN, ":utf8");
plugin Yancy => {
    backend => 'static:.',
    read_schema => 1,
    schema => {
        pages => {
            properties => {
                # Add an optional 'author' field
                author => { type => [ 'string', 'null' ] },
            },
        },
    },
};
get '/*id', {
    controller => 'yancy',
    action => 'get',
    schema => 'pages',
    template => 'default',
    layout => 'default',
    id => 'index',
};
app->start;
__DATA__
@@ default.html.ep
% title $item->{title};
<%== $item->{html} %>
@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
<head>
    <title><%= title %></title>
    <link rel="stylesheet" href="/yancy/bootstrap.css">
</head>
<body>
    <main class="container">
        %= content
    </main>
    <script src="/yancy/jquery.js"></script>
    <script src="/yancy/bootstrap.js"></script>
</body>
</html>

[error] Error setting item with ID "as/ss" in schema "pages": Wide character in syswrite at /home/dagandre/perl5/perlbrew/perls/perl-5.28.2/lib/site_perl/5.28.2/x86_64-linux/IO/Handle.pm line 481.

I try to edit site created by Statocles.

perl ./myapp.pl backend copy static:. pages
Wide character in syswrite at /home/dagandre/perl5/perlbrew/perls/perl-5.28.2/lib/site_perl/5.28.2/x86_64-linux/IO/Handle.pm line 481.

**Comment by rabbiveesh** [comment]
Errors like that usually mean that you didn't encode/decode your input.

What data is triggering that error?

**Comment by dagmatritsa** [comment]
My ENV
COLORTERM  =  truecolor
DBUS_SESSION_BUS_ADDRESS  =  unix:path=/run/user/1000/bus
DESKTOP_SESSION  =  lightdm-xsession
DISPLAY  =  :0.0
GDMSESSION  =  lightdm-xsession
GLADE_CATALOG_PATH  =  :
GLADE_MODULE_PATH  =  :
GLADE_PIXMAP_PATH  =  :
GTK_MODULES  =  gail:atk-bridge
HOME  =  /home/dagandre
LANG  =  ru_RU.UTF-8
LANGUAGE  =  ru_RU.UTF-8
LC_ALL  =  ru_RU.UTF-8
LOGNAME  =  dagandre
LS_COLORS  =  rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
MANPATH  =  /home/dagandre/perl5/perlbrew/perls/perl-5.30.1/man:/usr/local/man:/usr/local/share/man:/usr/share/man
PATH  =  /home/dagandre/perl5/perlbrew/bin:/home/dagandre/perl5/perlbrew/perls/perl-5.30.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/dagandre/perl5/bin
PERLBREW_HOME  =  /home/dagandre/.perlbrew
PERLBREW_MANPATH  =  /home/dagandre/perl5/perlbrew/perls/perl-5.30.1/man
PERLBREW_PATH  =  /home/dagandre/perl5/perlbrew/bin:/home/dagandre/perl5/perlbrew/perls/perl-5.30.1/bin
PERLBREW_PERL  =  perl-5.30.1
PERLBREW_ROOT  =  /home/dagandre/perl5/perlbrew
PERLBREW_SHELLRC_VERSION  =  0.87
PERLBREW_VERSION  =  0.87
PWD  =  /home/dagandre
QT_ACCESSIBILITY  =  1
SESSION_MANAGER  =  local/kloeiruyg3921:@/tmp/.ICE-unix/723,unix/kloeiruyg3921:/tmp/.ICE-unix/723
SHELL  =  /bin/bash
SHLVL  =  1
SSH_AGENT_PID  =  713
SSH_AUTH_SOCK  =  /tmp/ssh-6ptOSiecacZX/agent.682
TERM  =  xterm-256color
USER  =  dagandre
VTE_VERSION  =  5402
WINDOWID  =  61225703
XAUTHORITY  =  /home/dagandre/.Xauthority
XDG_CONFIG_DIRS  =  /etc/xdg
XDG_CURRENT_DESKTOP  =  XFCE
XDG_DATA_DIRS  =  /usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share
XDG_GREETER_DATA_DIR  =  /var/lib/lightdm/data/dagandre
XDG_MENU_PREFIX  =  xfce-
XDG_RUNTIME_DIR  =  /run/user/1000
XDG_SEAT  =  seat0
XDG_SEAT_PATH  =  /org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS  =  user
XDG_SESSION_DESKTOP  =  lightdm-xsession
XDG_SESSION_ID  =  2
XDG_SESSION_PATH  =  /org/freedesktop/DisplayManager/Session0
XDG_SESSION_TYPE  =  x11
XDG_VTNR  =  7
_  =  /home/dagandre/perl5/perlbrew/perls/perl-5.30.1/bin/perl

**Comment by dagmatritsa** [comment]
1. It's not work
PRAGMA encoding = "UTF-8";
2. state $db = Mojo::SQLite->new( 'sqlite:' . app->home->child( 'docs.db' ) ,{AutoCommit => 1, RaiseError => 1,sqlite_unicode => 1});
3. binmode(STDOUT, ":utf8");
binmode(STDIN, ":utf8");

**Comment by dagmatritsa** [comment]
my db

[myproj.tar.gz](https://github.com/preaction/Yancy/files/3878533/myproj.tar.gz)

**Comment by dagmatritsa** [comment]
with database work ok.
but while

perl ./myapp.pl backend copy static:. pages

Wide character in syswrite at /home/dagandre/perl5/perlbrew/perls/perl-5.30.1/lib/5.30.1/x86_64-linux/IO/Handle.pm line 481.

**Comment by preaction** [comment]
This is likely a bug in the Yancy::Backend::Static driver: I indeed do not do any encoding/decoding of input/output... I'll look to see what Statocles did to fix that and apply the same fix there. Thanks for the report!

**Comment by preaction** [comment]
I think this new release of Yancy::Backend::Static (v0.011) should fix this. Could you give it a try and let me know? Thanks!

**Comment by dagmatritsa** [comment]
Nice work!
Y r the best!

**Comment by preaction** [comment]
There was a [bug in Yancy::Backend::Static v0.011 that caused the tests to fail](/preaction/Yancy-Backend-Static/issues/10). I've just released v0.012 to fix that bug.
