### ISSUE TITLE
Test fails from postfix dereference

### ISSUE THREAD

**Issue by lindleyw** [preaction/Yancy#9]
Although `Makefile.PL` says `"MIN_PERL_VERSION" => "5.010"`, `t/lib/Local/Test.pm` at line 61 uses a postfix dereference as `->@[`  only made stable in v5.24:

    { rows => [ $list->@[1..$#$list] ], total => scalar @$list },

Suggested resolution: Either the line should be rewritten or the minimum Perl version should be v5.24.

**Comment by preaction** [comment]
Thanks for the report!
