### ISSUE TITLE
Example of usage of Yancy::Plugin::Editor::route - URL customization

### ISSUE THREAD

**Issue by pavelsr** [preaction/Yancy#90]
Hi Doug,

Could you please provide an example of usage [route](https://metacpan.org/pod/Yancy::Plugin::Editor#route) config param?

My purpose is to customize URL - set `/admin` instead of `/yancy`. 

I don't understand how it's possible to do with config - seems like [Yancy::Plugin::Editor code](https://github.com/preaction/Yancy/blob/master/lib/Yancy/Plugin/Editor.pm#L192) expect Mojolicious::Routes::Route object, not a string.

If I set `route => 'admin'` or `route => '/admin'` I get `Can't locate object method "to" via package ".admin"` error

Setting `app->routes->any( '/admin' )->name('admin');` gives same error.

**Comment by preaction** [comment]
Ah, yes, there should be an example there. Also, it could see if it got a string and make the right route for you. But, here's how it works:

```
sub startup( $app ) {
    my $route = $app->routes->any( '/admin' );
    $app->plugin( Yancy => {
        ...
        editor => {
            route => $route,
        },
    } );
}
```

So it's not possible using the standalone `yancy` command just yet.

**Comment by pavelsr** [comment]
Ok, got it. So for now it's impossible to customize URL just by string in config, need to redefine it in startup.
